[nl]
  languageName = "NL"
  languageCode = "nl-nl"
  contentDir = "content/nederlands"
  weight = 1
[en]
  languageName = "EN"
  languageCode = "en-uk"
  contentDir = "content/english"
  weight = 2