############# Dutch navigation ##############

# main menu
[[main]]
name = "Particulier"
url = "/individual"
weight = 1

[[main]]
name = "Zakelijk"
url = "/business"
weight = 2

# individual menu
[[individual]]
name = "Home"
url = "/individual"
weight = 1

[[individual]]
name = "Waarom"
url = "/individual/why"
weight = 2

  [[individual]]
  name = "Veilig"
  url = "/individual/why/secure"
  weight = 1
  parent = "Waarom"

  [[individual]]
  name = "Privacy"
  url = "/individual/why/privacy"
  weight = 2
  parent = "Waarom"

[[individual]]
name = "Hulp nodig?"
url = "/individual/need-help "
weight = 3

# business menu
[[business]]
name = "Home"
url = "/business"
weight = 1

[[business]]
name = "Services"
url = "/business/services"
weight = 2

  [[business]]
  name = "Overzicht"
  url = "/business/services/overview"
  weight = 1
  parent = "Services"

  [[business]]
  name = "Identificatie"
  url = "/business/services/identification"
  weight = 2
  parent = "Services"

[[business]]
name = "Werken bij"
url = "/business/carreer"
weight = 3

# footer menu
[[footer]]
name = "Over"
url = "about"
weight = 1

[[footer]]
name = "Elementen"
url = "elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 3
